name: Workflow1

"on":
  pull_request:
    branches:
      - main

jobs:
    CI: 
     runs-on: ubuntu-latest
     outputs:
      Deploy-Reviews: ${{ steps.filter.outputs.reviews }}
      Deploy-Reports: ${{ steps.filter.outputs.reports }}
     strategy:
      matrix:
        node-version: [16.x]
     permissions:
      pull-requests: read

     steps:
      - name: Checkout
        uses: actions/checkout@v2
        
    
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
           reviews:
            - 'packages/reviews/*'
           reports:
            - 'packages/reports/*'

      - name: Deploy Reviews
        if: steps.filter.outputs.reviews == 'true'
        run: echo "reviews=true" >> "$GITHUB_OUTPUT"
      
      - name: Deploy Reports
        if: steps.filter.outputs.reports == 'true'
        run: echo "reports=true" >> "$GITHUB_OUTPUT"

    Call-workflow:
        needs: CI
        strategy:
            matrix:
                node-version: [16.x]
                packages: [reviews, reports]
        uses: ./.github/workflows/reusable.yml
        with:
            mode: "development"
            package: "reviews"
        secrets:
            TEST_VALUE: "1234"
            