name: Workflow1

"on":
  pull_request:
    branches:
      - main

jobs:
    CI: 
     runs-on: ubuntu-latest
     outputs:
      changed-packages: ${{ steps.filter.outputs.changes }}
     strategy:
      matrix:
        node-version: [16.x]
     permissions:
      pull-requests: read

     steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
    
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
           reviews:
            - 'packages/reviews/*'
           reports:
            - 'packages/reports/*'

    Call-workflow:
        needs: CI
        strategy:
         matrix:
           package: ${{ fromJSON(needs.changes.outputs.changed-packages) }}

        uses: ./.github/workflows/reusable.yml
        with:
            mode: "development"
            package: ${{ matrix.packages }}
        secrets:
            TEST_VALUE: "1234"
            